language: node_js
env:
  - NODE_ENV=test MONGO_URI__TEST=mongodb://localhost:27017/unehub-test JWT_SECRET=skrrrt
node_js:
  - node # latest stable Node.js release
services:
  - mongodb
cache:
  directories:
    - 'node_modules' # cache to avoid installing all dependencies every build
