language: node_js
node_js:
  - node # latest stable Node.js release
env:
  - NODE_ENV=test MONGO_URI__TEST=mongodb://localhost:27017/test JWT_SECRET=skrrrt
cache:
  directories:
    - 'node_modules' # cache to avoid installing all dependencies every build
services:
  - mongodb
