version: '3'
services:
  app:
    container_name: unehub_app_test
    restart: always
    tty: true # resepects console colors
    # build the unehub_app image using the Dockerfile in the current directory
    build:
      # Either a path to a directory containing a Dockerfile, or a url to a git repository. 
      # When the value supplied is a relative path, it is interpreted as relative to the location of the Compose file.
      context: .
      # Alternate Dockerfile. 
      # Compose uses an alternate file to build with. A build path must also be specified.
      dockerfile: Dockerfile.test
    ports:
      # map the host port to the container port
      - '80:8000'
    # link app container to mongo container
    depends_on:
      - mongo
  mongo:
    container_name: unehub_mongo_test
    restart: always
    tty: true
    # instaed of building our own mongo image, pull the standard mongo image from
    # the Docker Hub registry
    image: mongo
    ports:
      - '27017:27017'
    # volumes:
    #   - ./data/db:/data/db