version: '3'
services:
  web:
    build: ./ # the relative location to the build context (our local Dockerfile)
    command: nodemon server.js # will override the CMD in Dockerfile
    tty: true # respects console colors
    volumes:
      # leverage bind-mounting this says take my current dir and bind-mount it on /usr/src/app inside my container
      - ./:/usr/src/app
    ports:
      - '80:8000'
    depends_on:
      - mongo
    restart: always
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - ./mongodb_persist:/data/db # persist the data from docker's mongodb in a local file
